// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQ7YrBBmdOpR5CNq_jHjwLxNlDA-8Eag',
    appId: '1:612063049561:web:ff7967b8f3a2fecd187e48',
    messagingSenderId: '612063049561',
    projectId: 'weatherapp-5113c',
    authDomain: 'weatherapp-5113c.firebaseapp.com',
    storageBucket: 'weatherapp-5113c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_Bn5orSXlTyBJirGsdJrRAXEwfg8RvQ',
    appId: '1:612063049561:android:cc0e4265529dce16187e48',
    messagingSenderId: '612063049561',
    projectId: 'weatherapp-5113c',
    storageBucket: 'weatherapp-5113c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2tYwrrYiGtZaoheRHAgKdZBCMXtKaVM',
    appId: '1:612063049561:ios:3c7c22ccd7101923187e48',
    messagingSenderId: '612063049561',
    projectId: 'weatherapp-5113c',
    storageBucket: 'weatherapp-5113c.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2tYwrrYiGtZaoheRHAgKdZBCMXtKaVM',
    appId: '1:612063049561:ios:3c7c22ccd7101923187e48',
    messagingSenderId: '612063049561',
    projectId: 'weatherapp-5113c',
    storageBucket: 'weatherapp-5113c.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRQ7YrBBmdOpR5CNq_jHjwLxNlDA-8Eag',
    appId: '1:612063049561:web:b75fbc191828ca99187e48',
    messagingSenderId: '612063049561',
    projectId: 'weatherapp-5113c',
    authDomain: 'weatherapp-5113c.firebaseapp.com',
    storageBucket: 'weatherapp-5113c.firebasestorage.app',
  );
}
